### PR TITLE
workaround aiosmtplib issues with port 587

### PR DESCRIPTION
**Pull request by nihlaeth**
workaround for this issue when working with SMTP_PORT 587
```
======== Running on http://0.0.0.0:8000 ========
(Press CTRL+C to quit)
Can not send email
Traceback (most recent call last):
  File "/git/dnd/lib64/python3.6/site-packages/aiosmtplib/connection.py", line 46, in create_connection
    connect_future, timeout=timeout, loop=loop)
  File "/usr/lib64/python3.6/asyncio/tasks.py", line 352, in wait_for
    return fut.result()
  File "/usr/lib64/python3.6/asyncio/base_events.py", line 802, in create_connection
    sock, protocol_factory, ssl, server_hostname)
  File "/usr/lib64/python3.6/asyncio/base_events.py", line 828, in _create_connection_transport
    yield from waiter
  File "/usr/lib64/python3.6/asyncio/sslproto.py", line 503, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "/usr/lib64/python3.6/asyncio/sslproto.py", line 201, in feed_ssldata
    self._sslobj.do_handshake()
  File "/usr/lib64/python3.6/ssl.py", line 683, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: UNKNOWN_PROTOCOL] unknown protocol (_ssl.c:749)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/git/dnd/aiohttp-login/aiohttp_login/handlers.py", line 96, in registration
    'link': link,
  File "/git/dnd/aiohttp-login/aiohttp_login/utils.py", line 132, in render_and_send_mail
    await send_mail(to, subject.strip(), body)
  File "/git/dnd/aiohttp-login/aiohttp_login/utils.py", line 116, in send_mail
    await smtp.connect()
  File "/git/dnd/lib64/python3.6/site-packages/aiosmtplib/connection.py", line 173, in connect
    timeout=self.timeout)
  File "/git/dnd/lib64/python3.6/site-packages/aiosmtplib/connection.py", line 50, in create_connection
    host=hostname, port=port, err=err))
aiosmtplib.errors.SMTPConnectError: Error connecting to 192.168.1.6 on port 587: [SSL: UNKNOWN_PROTOCOL] unknown protocol (_ssl.c:749)
```

### CODE REVIEW

**Comment by imbolc** [comment]
Hey, @nihlaeth , thanks for your PR. I don't know about smtp, can't we use this workaround for any ports? I mean can we use it as only option?

**Comment by nihlaeth** [comment]
Thank you for writing this library, you saved me a lot of work.

I'm no expert on SMTP either,  it's just my luck that I set up a mail server only two days ago. From what I understand, we can't use this workaround all the time. There's a difference between SSL and TLS,  and aiosmtp does not make this distinction unfortunately. If you want to support SMTP servers exposing port 4 something something (which is exclusively SSL I believe), you need to initiate an encrypted connection instead of plain text one like with TLS. For all I know some SMTP servers accept encrypted connections on port 25 and 587 as well, depending on their configuration…

I opened an issue about this at aiosmtp , but as I don't know the SMTP protocol well enough to provide them with a pull request, I don't know how long it's going to take.

**Comment by imbolc** [comment]
I see, thank you @nihlaeth , I've updated pypi release

**Comment by nihlaeth** [comment]
I was just about to inform you about the bug I introduced at rule 140 after @sietse did a quick code review for me, only to see that you had already fixed it. Thanks!

**Pull request merged**
