### PR TITLE
allow the use of themes from outside the aiohttp_login directory

### PR DESCRIPTION
**Pull request by nihlaeth**
allow users to create their own themes inside their own packages

### CODE REVIEW

**Comment by imbolc** [comment]
Hey @nihlaeth :) Why don't you use [jinja-app-loader](https://github.com/imbolc/jinja_app_loader)? You can change (and add) any templates of `aiohttp-login`. I think, I have to mention this in the docs..

**Comment by nihlaeth** [comment]
Docs would be great, I couldn't get it to work... But there's another reason why I prefer this method. From a quick source code inspection, it doesn't look like jinja-app-loader supports running from gzipped packages.

**Comment by imbolc** [comment]
@nihlaeth you, sure, actually I don't know anything about gzipped packages :)

**Comment by nihlaeth** [comment]
There is some info about it in the [setuptools docs](http://setuptools.readthedocs.io/en/latest/pkg_resources.html#resourcemanager-api) if you're interested. It's possible to run Python packages from inside of archives, and pip will try to install packages compressed if possible. But that means the resources inside the package directory won't have a path in any real sense, nor does any module inside the package. To access resources you have to use the ResourceManager API from pkg_resources.

**Comment by imbolc** [comment]
@nihlaeth look at example now, you'll see how to change base template of aiohttp-login. This way you can just extend `templates/aiohttp_login/bootstrap-4/base.html` with your project base template.

**Comment by nihlaeth** [comment]
That was clear to me, just not how to get  jinja-app-loader working. Jinja kept complaining about not being able to find my templates. And with my own loader, aiohttp-login couldn't find its templates, so before I wrote my own theme I just used the chained loader provided by jinja and fed it both  jinja-app-loader and the regular file loader with a resource manager directory. Only that method doesn't work when you want aiohttp-login to use a non-built-in template. Hence this pull request.

I prefer not to make changes inside third party package directories anyway, since it makes keeping everything up to date with pip a pain.

**Comment by imbolc** [comment]
You know, my real intention of this project is to find a way to write reusable apps (like django apps) for aiohttp. I think the absence of built-in abilities to write such apps is the main reason of why aiohttp is still not so popular.

**Comment by nihlaeth** [comment]
That, and probably that most people find asynchronous stuff really confusing. Plus it's exclusive to Python 3 users, which doesn't help matters with Python 2 still being the default in Linux systems. aiohttp is better suited for people who like to get their hands dirty, and don't mind reading documentation or even source code instead of tutorials.

You're doing awesome work here in any case, a login library like this makes writing websites with aiohttp so much easier.

**Comment by imbolc** [comment]
Have you seen [sanic](https://github.com/channelcat/sanic)? It got more stars in a month than aiohttp in the all this years :) I think it's not because its "speed", but because of its flasky. So it seems like py3 and async is not so big problem for people anymore.

**Comment by imbolc** [comment]
I still don't understand why jinja-app-loader doesn't work for you. Maybe you could change example of aiohttp-login to make it nonworking this way?

**Comment by nihlaeth** [comment]
Sanic looks promising, if those benchmarks  scale well to heavier pages, I'm definitely porting my projects. Maybe you're right and the lack of apps is the problem for aiohttp.

I'll show you how I used your example: [early version of my website](https://github.com/nihlaeth/dnd/blob/52575f2a1f03da1830ca57263ebbdb787e449463/dnd/__init__.py)

I didn't make a nonworking commit, but if you remove rule 23 and 24, you should see the failure.

**Comment by imbolc** [comment]
I'm just curious, why do you want to install your site like a pip package?

**Comment by nihlaeth** [comment]
Because then I can install dependencies automatically, easily create scripts to run it as a daemon (which work on both Linux and Windows), and it's put in the right place automatically (meaning in the Python path). And I can easily share my site  this way, by publishing it on pypi. Plus you can make use of the plug-in system that setuptools provides. Basically tons of reasons, and I'm probably forgetting to mention a couple of important ones.

**Comment by imbolc** [comment]
Haven't you forgotten about inability to use virtualenv this way? I think this drawback negates all the tons of reasons :)

**Comment by nihlaeth** [comment]
Why couldn't you use virtualenv this way? I'm using it that way right now.

**Comment by imbolc** [comment]
Do you mean, it possible to install two different version of package within the same environment?

**Comment by imbolc** [comment]
Anyway, have you tried to provide `root_dir` parameter to `jinja_app_loader`?

**Comment by nihlaeth** [comment]
I have, it didn't work for me. It's entirely possible that I did that wrong though, I didn't spend very long debugging it.

> Do you mean, it possible to install two different version of package within the same environment?

yes

**Comment by imbolc** [comment]
If I remember right, the inability to install different versions of packages was the main reason of creating virtualenv. Maybe you confusing pip with npm? I've made a little research right now, and don't see any changes, could you give me link to any mentions of this in docs?

**Comment by nihlaeth** [comment]
I think we misunderstand each other, I didn't mean that virtualenv is obsolete now, what I meant is that you can use pip together with virtualenv. Although to be precise, virtualenv is deprecated in python 3, and we should now use `python -m venv my_environment`. But together with a separate python binary, a pip binary is installed there are also, so you can use it to install packages into the virtual environment.

```
$ python -m venv test
$ ls test/bin
activate  activate.csh  activate.fish  easy_install*  easy_install-3.5*  pip*  pip3*  pip3.5*  python@  python3@  python3.5@
```

**Comment by imbolc** [comment]
> And I can easily share my site this way, by publishing it on pypi.

If you meant here to install your site without virtualenv, it's a bad idea. Because any updates of any package it rely, may cause problems.

**Comment by nihlaeth** [comment]
We're talking about different things here. Publishing on pypi has nothing to do with using virtualenv. You can use pip both with the system python and with a virtual environment.

Usually a virtual environment is used in development. In deployment situations you want to use the system Python. To make sure dependencies have the right versions, you can indicate specific versions or even version ranges in the setup.py file.

**Comment by imbolc** [comment]
@nihlaeth Don't waste your time with sanic, there is already https://github.com/squeaky-pl/japronto/
They are fucking crazy that guys :)

**Comment by nihlaeth** [comment]
I am aware, but thanks for the tip anyway

**Comment by imbolc** [comment]
Anyway I don't see any sense to write usual sites on something except of aiohttp. Sanic follows this wierd syntax of flask and don't have a lot of aiohttp functionality. Japronto seems good for thin service modules, but not more. Have you tried to profile your site? What part of the resources aiohttp takes?

**Comment by nihlaeth** [comment]
Well actually, I stole a trick from sanic and started using uvloop. I didn't run any actual benchmarks, but it felt a LOT faster. Unfortunately aiosmtplib doesn't integrate with that yet, due to starttls being poorly supported by asyncio.

aiohttp is fine for my purposes, but I have a weak spot for cool projects like sanic and japronto.

**Pull request merged**
