### PR TITLE
allow users to override common directory templates

### PR DESCRIPTION
**Pull request by nihlaeth**

### CODE REVIEW

**Comment by imbolc** [comment]
Maybe `jinja_app_loader` would be a better place to fix this? What do you think about changing it's API like:
```
def __init__(self, *, root_dir='templates', root_app=None, ...):
    assert not (root_dir and root_app), 'You should choose between these params'
```
And if the `root_app` is provided loader would find its templates folder like this: https://github.com/imbolc/jinja_app_loader/blob/master/jinja_app_loader.py#L47

**Comment by nihlaeth** [comment]
I'm up for that. Would you prefer me to make a pull request, or do you want to fix this yourself?

**Comment by imbolc** [comment]
Yes, PR would be great, thank you!

**Comment by nihlaeth** [comment]
I'm on it! I don't think I'll get to it today, but definitely this week.

**Pull request merged**
